In [2]:
import numpy as np

In [ ]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[4,4,7,8],[9,6,3,1]],[[5,0,9,3],[4,7,6,3]]])

In [ ]:
print(arr)
print(arr.shape)

In [ ]:
np.zeros((2, 3, 3))
aa = np.ones(2)
c = np.random.rand(2, 3, 4)

In [ ]:
np.arange(0,10,2)


In [ ]:
np.linspace(0,5,10)

Array properties

In [ ]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

<!-- Type conversion -->

Type conversion

In [ ]:
arr = np.array([1.2,2.5,3.4])
arr_int = arr.astype(int)
print(arr_int)

Indexing and slicing

In [ ]:
mat = np.array([[1,2,3,6],[5,6,7,8],[9,7,5,3]])
print(mat[:,:2])
print(mat[1:,1:])

In [ ]:
a = np.array([1,2,3])
#note b = a this is not safe and it change the original array
b = a.copy()
b[0] = 99
print(a,b)

In [ ]:
# arithmatic operations 
# (a+b),(a-b),(a*b),(a/b)
# (a+5),(a-5)
# possible scenarios
# np.sqrt,np.log,np.exp,np.min,np.max,np.mean,np.sum,np.std
mat = np.array([[1,2,3,6],[5,6,7,8],[9,7,5,3]])
print(mat>4)
print(mat[mat>4])

Element wise Multiplication
<!-- it maintains the shape, either matrix size should be a[n,n],b[n,n] or 
one of them shoulb be 1 like a[1,n],b[n,1] and a[n,n],b[1]  -->
<!-- shapes a[n,m],b[n] or a[n,n],b[n,m] is not compatible -->

Broadcasting Rule

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr + 10)

In [ ]:
row = np.array([1,2,3,4])
print(row + arr)

Matrix Multiplication

In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))
print(a.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


Random Module

In [11]:
np.random.rand(3,4)

array([[0.16503156, 0.17754643, 0.2875344 , 0.01263219],
       [0.47667365, 0.66718889, 0.60448202, 0.38918507],
       [0.26969426, 0.67787252, 0.16090059, 0.07337204]])

In [25]:
np.random.randint(3,50,10)
# patameters are 10 is no of elements 

array([20, 33, 19, 19, 48, 30, 47, 48, 37, 12])

Reshaping Arrays

In [28]:
arr = np.arange(15)
print(arr.reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


Axis in Numpy

In [36]:
arr = np.array([[1,2,3],[4,5,6]])
print(sum(arr))
print(np.sum(arr))
print(np.sum(arr, axis = 0))

[5 7 9]
21
[5 7 9]


Where in Numpy

In [42]:
arr = np.array([1,-3,20,-5,15])
result = np.where(arr<0,0,arr)
print(result)
result = np.where(arr %2 != 0, -1, arr)
print(result)

[ 1  0 20  0 15]
[-1 -1 20 -1 -1]


In [43]:
arr = np.array([50,45,67,89,39])
status = np.where(arr >=50,1,0)
print(status)

[1 0 1 1 0]


In [44]:
data  = np.array([10,20,30,40,50])
mean_val = np.mean(data)
result = np.where(data > mean_val, mean_val,data)
print(result)

[10. 20. 30. 30. 30.]


In [45]:
arr = np.array([[10,60,30],[80,20,50]])
result = np.where(arr>=50,1,0)
print(result)

[[0 1 0]
 [1 0 1]]


In [3]:
np.random.rand(3,4)

array([[0.18839526, 0.77053673, 0.11704863, 0.72307319],
       [0.23065005, 0.92674275, 0.71797237, 0.30037689],
       [0.78219362, 0.90121039, 0.3726205 , 0.35955797]])