In [1]:
import numpy as np

In [2]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[4,4,7,8],[9,6,3,1]],[[5,0,9,3],[4,7,6,3]]])

In [3]:
print(arr)
print(arr.shape)

[[[1 2 3 4]
  [5 6 7 8]]

 [[4 4 7 8]
  [9 6 3 1]]

 [[5 0 9 3]
  [4 7 6 3]]]
(3, 2, 4)


In [ ]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
aa = np.ones(2)
c = np.random.rand(2, 3, 4)
print(aa)
print(c)

[1. 1.]
[[[0.11830295 0.24427927 0.29748164 0.87838481]
  [0.9286212  0.40345591 0.35885852 0.38157839]
  [0.88385431 0.71886664 0.29896257 0.62934453]]

 [[0.16610121 0.53275623 0.90929115 0.31850788]
  [0.92875349 0.45312149 0.36264392 0.3015863 ]
  [0.30840562 0.19514313 0.41173753 0.88258871]]]


In [12]:
np.arange(0,10,0.5)


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [14]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

Array properties

In [ ]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

<!-- Type conversion -->

Type conversion

In [15]:
arr = np.array([1.2,2.5,3.4])
arr_int = arr.astype(int)
print(arr_int)

[1 2 3]


Indexing and slicing

In [ ]:
mat = np.array([[1,2,3,6],[5,6,7,8],[9,7,5,3]])
print(mat[:,:2])
print(mat[1:,1:])

In [ ]:
a = np.array([1,2,3])
#note b = a this is not safe and it change the original array
b = a.copy()
b[0] = 99
print(a,b)

In [ ]:
# arithmatic operations 
# (a+b),(a-b),(a*b),(a/b)
# (a+5),(a-5)
# possible scenarios
# np.sqrt,np.log,np.exp,np.min,np.max,np.mean,np.sum,np.std
mat = np.array([[1,2,3,6],[5,6,7,8],[9,7,5,3]])
print(mat>4)
print(mat[mat>4])

Element wise Multiplication
<!-- it maintains the shape, either matrix size should be a[n,n],b[n,n] or 
one of them shoulb be 1 like a[1,n],b[n,1] and a[n,n],b[1]  -->
<!-- shapes a[n,m],b[n] or a[n,n],b[n,m] is not compatible -->

Broadcasting Rule

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr + 10)

In [ ]:
row = np.array([1,2,3,4])
print(row + arr)

Matrix Multiplication

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))
print(a.T)

[[1 3]
 [2 4]]


Random Module

In [19]:
np.random.rand(3,4,3)

array([[[0.43400187, 0.65740415, 0.43245834],
        [0.76926938, 0.90502727, 0.9633387 ],
        [0.14654246, 0.72154556, 0.12433112],
        [0.00538039, 0.85058118, 0.07924483]],

       [[0.52226873, 0.39125388, 0.56450116],
        [0.43371331, 0.02059629, 0.57411251],
        [0.25832484, 0.60231581, 0.43544349],
        [0.98560414, 0.64179787, 0.86039362]],

       [[0.16031198, 0.26397451, 0.61423838],
        [0.20695785, 0.12114501, 0.09238213],
        [0.38792442, 0.18816098, 0.68436408],
        [0.56008817, 0.99854619, 0.97336029]]])

In [20]:
np.random.randint(3,50,10)
# patameters are 10 is no of elements 

array([30, 28,  5, 11, 14, 23, 23, 25, 11, 42])

Reshaping Arrays

In [21]:
arr = np.arange(15)
print(arr.reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


Axis in Numpy

In [23]:
arr = np.array([[1,2,3],[4,5,6]])
print(sum(arr))
print(np.sum(arr))
print(np.sum(arr, axis = 1))

[5 7 9]
21
[ 6 15]


Where in Numpy

In [ ]:
arr = np.array([1,-3,20,-5,15])
result = np.where(arr<0,0,arr)
print(result)
result = np.where(arr %2 != 0, -1, arr)
print(result)

In [ ]:
arr = np.array([50,45,67,89,39])
status = np.where(arr >=50,1,0)
print(status)

In [ ]:
data  = np.array([10,20,30,40,50])
mean_val = np.mean(data)
result = np.where(data > mean_val, mean_val,data)
print(result)

In [ ]:
arr = np.array([[10,60,30],[80,20,50]])
result = np.where(arr>=50,1,0)
print(result)

In [ ]:
np.random.rand(3,4)