shape 4,7
rows hostel
coloumn days

In [2]:
import numpy as np

In [3]:
values = np.random.randint(120,650,size=(4,7))
print(values)

[[595 287 190 486 622 220 590]
 [243 442 243 502 303 547 207]
 [359 552 299 581 466 567 642]
 [596 447 537 200 423 316 397]]


In [4]:
print(values.shape,values.ndim,values.size,values.dtype)

(4, 7) 2 28 int32


In [5]:
coloumn_mean = np.mean(values, axis=1)
row_means = np.mean(values, axis=0)

In [6]:
status = np.max(coloumn_mean)
status2 = np.max(row_means)
print(status)
print(f"{status2:.2f}")

495.14285714285717
459.00


In [7]:
status = np.where(values>550,values*1.20,values)
print(status)

[[714.  287.  190.  486.  746.4 220.  708. ]
 [243.  442.  243.  502.  303.  547.  207. ]
 [359.  662.4 299.  697.2 466.  680.4 770.4]
 [715.2 447.  537.  200.  423.  316.  397. ]]


In [8]:
status = np.where(values>row_means,True,False)
print(status)

[[ True False False  True  True False  True]
 [False  True False  True False  True False]
 [False  True False  True  True  True  True]
 [ True  True  True False False False False]]


In [9]:
print(values.reshape(1,28))
print(values.reshape(2,14))

[[595 287 190 486 622 220 590 243 442 243 502 303 547 207 359 552 299 581
  466 567 642 596 447 537 200 423 316 397]]
[[595 287 190 486 622 220 590 243 442 243 502 303 547 207]
 [359 552 299 581 466 567 642 596 447 537 200 423 316 397]]


In [10]:
backup = values
safe_backup = values.copy()
values[3,4] = 287
print(backup)
print(safe_backup)

[[595 287 190 486 622 220 590]
 [243 442 243 502 303 547 207]
 [359 552 299 581 466 567 642]
 [596 447 537 200 287 316 397]]
[[595 287 190 486 622 220 590]
 [243 442 243 502 303 547 207]
 [359 552 299 581 466 567 642]
 [596 447 537 200 423 316 397]]
