In [1]:
import numpy as np

In [3]:
arr = np.array([1500,3000,5000])
lists = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(arr.shape,arr.ndim)
print(lists.shape,lists.ndim)

(3,) 1
(3, 4) 2


In [4]:
lists = lists+2
print(lists)

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [5]:
result = np.dot(arr,lists)
print(result)
print(np.sqrt(lists))

[59000 77500 53000 75000]
[[3.46410162 4.12310563 3.16227766 3.74165739]
 [2.64575131 3.         2.44948974 2.82842712]
 [2.         2.23606798 2.         2.44948974]]


In [9]:
print(lists[1:2,:])
print(lists[:,:2])

[[7 9 6 8]]
[[12 17]
 [ 7  9]
 [ 4  5]]


In [12]:
print(lists[2:,3:])
print(lists[:2,:2])

[[6]]
[[12 17]
 [ 7  9]]


In [13]:
print(lists.reshape(1,12))

[[12 17 10 14  7  9  6  8  4  5  4  6]]


In [14]:
print(lists.reshape(2,6))

[[12 17 10 14  7  9]
 [ 6  8  4  5  4  6]]


In [15]:
print(np.linspace(0,100,10))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [19]:
print(np.random.randint(0,20,size=(3,4)))

[[17 14 11 13]
 [11 18  2  7]
 [ 1 19 19  0]]


In [35]:
np.random.rand(1,5)
# np.random.rand(3,4)

array([[0.2212531 , 0.70748766, 0.05861542, 0.39405831, 0.22073634]])

In [21]:
print(np.sum(lists))

102


In [23]:
print(np.sum(lists,axis=1))

[53 30 19]
