In [1]:
import numpy as np

In [2]:
marks = np.array([[78,85,90],
                [45,60,55],
                [88,92,95],
                [30,40,35],
                [65,70,75]])

In [3]:
print(marks.shape,marks.ndim)

(5, 3) 2


In [4]:
print(marks.size)
print(marks.dtype)

15
int32


In [5]:
print(marks[1:2])
print(marks[:,2])
print(marks[0,1])

[[45 60 55]]
[90 55 95 35 75]
85


In [6]:
row_means = np.mean(marks, axis=1)
row_mean = np.mean(marks, axis=0)

In [7]:
print(row_means)
print(row_mean)

[84.33333333 53.33333333 91.66666667 35.         70.        ]
[61.2 69.4 70. ]


In [8]:
status = np.where(row_means >=80)
print(status)

(array([0, 2], dtype=int64),)


In [9]:
print(marks+5)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


In [10]:
statuss = np.where(marks>=50,1,0)
print(statuss)

[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


In [11]:
st = np.where(marks<40,0,marks)
print(st)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]


In [12]:
a = np.where(row_means<50,0,np.where(row_means<70,6,np.where(row_means<85,8,10))) 
# grade = np.where(marks2 < 50, 0, np.where(marks2 < 70, 6, np.where(marks2 < 85 , 8, 10)))
print(a)


[ 8  6 10  0  8]


In [13]:
marks1 = marks.copy()
marks[0,0] = 0
print(marks)
print(marks1)

[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
